services:
  nim-server: 
    build: ./NimServer
    environment:
      - SERVER_TYPE=nim
    networks:
      - pg-network
  
  tictactoe-server: 
    build: ./NimServer
    environment:
      - SERVER_TYPE=tictactoe
    networks:
      - pg-network
  
  connect-four-server:
    build: ./NimServer
    environment:
      - SERVER_TYPE=connectfour
    networks:
      - pg-network
  
  orchestrator:
    build: ./Orchestrator
    ports:
      - 3000:3000
    networks:
      - pg-network
  
  website:
    build: ./Front/pacific-games
    ports:
      - 80:80
    networks:
      - pg-network


networks:
  pg-network:
    driver: bridge